service:
  account:
    url: http://account.default.svc.cluster.local/account
---
spring:
  config:
    activate:
      on-profile: local
server:
  port: 8082
service:
  account:
    url: http://localhost:8081/account